import 'package:flutter/material.dart';
import '../../services/room_service.dart';
class OnboardingScreen extends StatefulWidget{const OnboardingScreen({super.key,required this.roomService,required this.onConnected});final RoomService roomService;final VoidCallback onConnected;@override State<OnboardingScreen> createState()=>_OnboardingScreenState();}
class _OnboardingScreenState extends State<OnboardingScreen>{final _name=TextEditingController(),_code=TextEditingController();bool _joining=false,_busy=false;String? _error;DateTime? _startedOn;
 @override void dispose(){_name.dispose();_code.dispose();super.dispose();}
 Future<void> _go()async{if(_name.text.trim().isEmpty||(_joining&&_code.text.trim().isEmpty)||(!_joining&&_startedOn==null)){setState(()=>_error=_joining?'Enter your name and private code.':'Enter your name and the date your relationship started.');return;}setState((){_busy=true;_error=null;});try{if(_joining){await widget.roomService.joinRoom(roomCode:_code.text,displayName:_name.text);}else{final room=await widget.roomService.createRoom(_name.text);await widget.roomService.setRelationshipStartDate(room['room_id'].toString(),_startedOn!);}widget.onConnected();}catch(e){final x=e.toString();if(mounted)setState(()=>_error=x.contains('not found')?'That private code was not found.':x.contains('full')?'That Love Vault already has two people.':'Something went wrong. Please try again.');}finally{if(mounted)setState(()=>_busy=false);}}
 @override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(26),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:440),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[
  const Center(child:CircleAvatar(radius:34,backgroundColor:Color(0xFFE9365A),child:Icon(Icons.favorite,color:Colors.white,size:34))),const SizedBox(height:20),Text('Love Vault',textAlign:TextAlign.center,style:Theme.of(context).textTheme.headlineLarge),const SizedBox(height:8),Text('One private place. Just the two of you.',textAlign:TextAlign.center,style:Theme.of(context).textTheme.bodyLarge),const SizedBox(height:30),
  Container(padding:const EdgeInsets.all(6),decoration:BoxDecoration(color:const Color(0xFFFFF1F4),borderRadius:BorderRadius.circular(24)),child:Row(children:[Expanded(child:_ModeButton(label:'Create ours',selected:!_joining,onTap:()=>setState(()=>_joining=false))),Expanded(child:_ModeButton(label:'Join partner',selected:_joining,onTap:()=>setState(()=>_joining=true)))])),const SizedBox(height:22),
  TextField(controller:_name,maxLength:50,decoration:const InputDecoration(labelText:'Your name',prefixIcon:Icon(Icons.person_outline))),if(!_joining)...[const SizedBox(height:10),ListTile(shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18),side:const BorderSide(color:Color(0xFFE7DDE0))),leading:const Icon(Icons.favorite_outline,color:Color(0xFFE9365A)),title:Text(_startedOn==null?'When did your relationship begin?':'${_startedOn!.day}/${_startedOn!.month}/${_startedOn!.year}'),subtitle:const Text('This becomes your anniversary date.'),onTap:()async{final now=DateTime.now();final d=await showDatePicker(context:context,firstDate:DateTime(1950),lastDate:now,initialDate:_startedOn??now);if(d!=null&&mounted)setState(()=>_startedOn=d);})],if(_joining)...[const SizedBox(height:10),TextField(controller:_code,textCapitalization:TextCapitalization.characters,decoration:const InputDecoration(labelText:'Private code',hintText:'AB12-CD34',prefixIcon:Icon(Icons.lock_outline)))],
  if(_error!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text(_error!,textAlign:TextAlign.center,style:TextStyle(fontFamily:'sans-serif',color:Theme.of(context).colorScheme.error))),const SizedBox(height:18),
  FilledButton.icon(onPressed:_busy?null:_go,icon:Icon(_joining?Icons.favorite_outline:Icons.add),label:Text(_busy?'Connecting…':_joining?'Join our Love Vault':'Create our Love Vault')),const SizedBox(height:16),
  const Row(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.lock_outline,size:16,color:Color(0xFF8A8587)),SizedBox(width:6),Text('Private by design • maximum two people',style:TextStyle(fontFamily:'sans-serif',color:Color(0xFF8A8587)))])
 ]))))));
}
class _ModeButton extends StatelessWidget{const _ModeButton({required this.label,required this.selected,required this.onTap});final String label;final bool selected;final VoidCallback onTap;@override Widget build(BuildContext context)=>InkWell(borderRadius:BorderRadius.circular(20),onTap:onTap,child:AnimatedContainer(duration:const Duration(milliseconds:180),padding:const EdgeInsets.symmetric(vertical:13),decoration:BoxDecoration(color:selected?Colors.white:Colors.transparent,borderRadius:BorderRadius.circular(20),boxShadow:selected?[const BoxShadow(color:Color(0x11000000),blurRadius:8)]:null),child:Text(label,textAlign:TextAlign.center,style:TextStyle(fontFamily:'sans-serif',fontWeight:FontWeight.w600,color:selected?const Color(0xFFE9365A):const Color(0xFF777174)))));}