import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class PromisesScreen extends StatefulWidget{const PromisesScreen({super.key,required this.vaultId});final String vaultId;@override State<PromisesScreen> createState()=>_PromisesScreenState();}
class _PromisesScreenState extends State<PromisesScreen>{final _db=Supabase.instance.client;bool _busy=false;List<Map<String,dynamic>> _items=[];
@override void initState(){super.initState();_load();}
Future<void> _load()async{final x=await _db.from('promises').select('id,title,body,created_by,created_at').eq('vault_id',widget.vaultId).order('created_at');if(mounted)setState(()=>_items=[for(final v in x)Map<String,dynamic>.from(v)]);}
Future<void> _editor()async{final title=TextEditingController(),body=TextEditingController();final save=await showModalBottomSheet<bool>(context:context,isScrollControlled:true,builder:(c)=>Padding(padding:EdgeInsets.fromLTRB(20,20,20,MediaQuery.viewInsetsOf(c).bottom+24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('A promise to us',style:Theme.of(c).textTheme.headlineSmall),const SizedBox(height:8),const Text('Something you want the two of you to remember and protect together.'),const SizedBox(height:18),TextField(controller:title,maxLength:80,decoration:const InputDecoration(labelText:'Promise title')),const SizedBox(height:10),TextField(controller:body,maxLength:1000,minLines:3,maxLines:7,decoration:const InputDecoration(labelText:'What are you promising?')),const SizedBox(height:16),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Save our promise'))])));if(save!=true||title.text.trim().isEmpty||body.text.trim().isEmpty)return;setState(()=>_busy=true);try{await _db.from('promises').insert({'vault_id':widget.vaultId,'created_by':_db.auth.currentUser!.id,'title':title.text.trim(),'body':body.text.trim()});await _load();}finally{if(mounted)setState(()=>_busy=false);}}
Future<void> _delete(Map<String,dynamic> p)async{final yes=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Remove this promise?'),content:const Text('This removes it from your shared list.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Keep it')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Remove'))]));if(yes==true){await _db.from('promises').delete().eq('id',p['id']);await _load();}}
@override Widget build(BuildContext context){final uid=_db.auth.currentUser?.id;return Scaffold(appBar:AppBar(title:const Text('Our Promises')),floatingActionButton:FloatingActionButton.extended(onPressed:_busy?null:_editor,icon:const Icon(Icons.add),label:const Text('New promise')),body:ListView(padding:const EdgeInsets.fromLTRB(20,12,20,110),children:[Text('Our Promises',style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:7),Text('A small place for the words you choose to live by together.',style:Theme.of(context).textTheme.bodyLarge),const SizedBox(height:20),if(_items.isEmpty)Container(padding:const EdgeInsets.all(26),decoration:BoxDecoration(color:const Color(0xFFFFF3F5),borderRadius:BorderRadius.circular(26)),child:const Column(children:[Icon(Icons.favorite_outline,size:42),SizedBox(height:12),Text('No promises yet.'),SizedBox(height:5),Text('Create the first one together.',textAlign:TextAlign.center)])),for(final p in _items)...[Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.favorite_outline,size:20),const SizedBox(width:9),Expanded(child:Text(p['title'].toString(),style:Theme.of(context).textTheme.titleLarge)),if(p['created_by']==uid)IconButton(onPressed:()=>_delete(p),icon:const Icon(Icons.delete_outline),tooltip:'Remove')]),const SizedBox(height:9),Text(p['body'].toString(),style:Theme.of(context).textTheme.bodyLarge)]))),const SizedBox(height:12)]]));}}
