import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class VaultActivityScreen extends StatefulWidget{const VaultActivityScreen({super.key,required this.vaultId});final String vaultId;@override State<VaultActivityScreen> createState()=>_VaultActivityScreenState();}
class _VaultActivityScreenState extends State<VaultActivityScreen>{final _db=Supabase.instance.client;bool _loading=true;List<_Activity> _items=[];
@override void initState(){super.initState();_load();}
Future<void> _load()async{final r=await Future.wait([_db.from('memories').select('title,created_at').eq('vault_id',widget.vaultId).order('created_at',ascending:false).limit(20),_db.from('promises').select('title,created_at').eq('vault_id',widget.vaultId).order('created_at',ascending:false).limit(20),_db.from('ask_me').select('question,created_at').eq('vault_id',widget.vaultId).order('created_at',ascending:false).limit(20),_db.from('surprises').select('title,created_at').eq('vault_id',widget.vaultId).order('created_at',ascending:false).limit(20)]);final x=< _Activity>[];for(final v in r[0])x.add(_Activity('Memory added',v['title']?.toString()??'A memory',v['created_at'],Icons.photo_outlined));for(final v in r[1])x.add(_Activity('Promise added',v['title']?.toString()??'A promise',v['created_at'],Icons.favorite_outline));for(final v in r[2])x.add(_Activity('Question asked',v['question']?.toString()??'A question',v['created_at'],Icons.chat_bubble_outline));for(final v in r[3])x.add(_Activity('Surprise created',v['title']?.toString()??'A surprise',v['created_at'],Icons.card_giftcard_outlined));x.sort((a,b)=>b.date.compareTo(a.date));if(mounted)setState((){_items=x.take(50).toList();_loading=false;});}
String _when(DateTime d){final now=DateTime.now(),local=d.toLocal(),diff=now.difference(local);if(diff.inMinutes<1)return 'Just now';if(diff.inHours<1)return '${diff.inMinutes}m ago';if(diff.inDays<1)return '${diff.inHours}h ago';if(diff.inDays<7)return '${diff.inDays}d ago';return '${local.day}/${local.month}/${local.year}';}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Vault Activity')),body:_loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.fromLTRB(20,18,20,60),children:[Text('Vault Activity',style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:7),Text('A simple history of what has been added to your shared space.',style:Theme.of(context).textTheme.bodyLarge),const SizedBox(height:22),if(_items.isEmpty)Container(padding:const EdgeInsets.all(26),decoration:BoxDecoration(color:const Color(0xFFFFF5F6),borderRadius:BorderRadius.circular(26)),child:const Column(children:[Icon(Icons.history_rounded,size:42),SizedBox(height:12),Text('Your activity will appear here.'),SizedBox(height:5),Text('Memories, promises, questions and surprises will build your shared history.',textAlign:TextAlign.center)]))else for(final a in _items)...[Card(child:ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:18,vertical:8),leading:CircleAvatar(child:Icon(a.icon,size:20)),title:Text(a.kind),subtitle:Text(a.text,maxLines:2,overflow:TextOverflow.ellipsis),trailing:Text(_when(a.date),style:Theme.of(context).textTheme.labelSmall))),const SizedBox(height:8)]])));
}
class _Activity{_Activity(this.kind,this.text,dynamic raw,this.icon):date=DateTime.tryParse(raw?.toString()??'')??DateTime.fromMillisecondsSinceEpoch(0);final String kind,text;final DateTime date;final IconData icon;}
