import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class SavedScreen extends StatefulWidget{const SavedScreen({super.key,required this.vaultId});final String vaultId;@override State<SavedScreen> createState()=>_SavedScreenState();}
class _SavedScreenState extends State<SavedScreen>{final _db=Supabase.instance.client;bool _loading=true;List<Map<String,dynamic>> _memories=[],_promises=[];
@override void initState(){super.initState();_load();}
Future<void> _load()async{final results=await Future.wait([_db.from('memories').select('id,title,body,memory_date').eq('vault_id',widget.vaultId).eq('is_featured',true).order('memory_date',ascending:false),_db.from('promises').select('id,title,body,created_at').eq('vault_id',widget.vaultId).order('created_at',ascending:false)]);if(mounted)setState((){_memories=[for(final v in results[0])Map<String,dynamic>.from(v)];_promises=[for(final v in results[1])Map<String,dynamic>.from(v)];_loading=false;});}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Saved')),body:_loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.fromLTRB(20,18,20,60),children:[Text('Saved',style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:7),Text('The pieces of your relationship worth keeping close.',style:Theme.of(context).textTheme.bodyLarge),const SizedBox(height:24),_Section(title:'Featured memories',icon:Icons.bookmark_outline,empty:'Feature a memory and it will appear here.',items:_memories),const SizedBox(height:24),_Section(title:'Our promises',icon:Icons.favorite_outline,empty:'Your promises will appear here once you create them.',items:_promises)])));
}
class _Section extends StatelessWidget{const _Section({required this.title,required this.icon,required this.empty,required this.items});final String title,empty;final IconData icon;final List<Map<String,dynamic>> items;
@override Widget build(BuildContext context)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Icon(icon),const SizedBox(width:9),Text(title,style:Theme.of(context).textTheme.titleLarge)]),const SizedBox(height:12),if(items.isEmpty)Container(width:double.infinity,padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:const Color(0xFFFFF6F7),borderRadius:BorderRadius.circular(22)),child:Text(empty))else for(final item in items)...[Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(item['title']?.toString().trim().isNotEmpty==true?item['title'].toString():'Untitled',style:Theme.of(context).textTheme.titleMedium),if(item['body']?.toString().trim().isNotEmpty==true)...[const SizedBox(height:7),Text(item['body'].toString(),maxLines:4,overflow:TextOverflow.ellipsis)]]))),const SizedBox(height:9)]]);}
