import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../services/room_service.dart';

class OurStoryScreen extends StatefulWidget{const OurStoryScreen({super.key,required this.vaultId});final String vaultId;@override State<OurStoryScreen> createState()=>_OurStoryScreenState();}
class _OurStoryScreenState extends State<OurStoryScreen>{late final RoomService _rooms;Map<String,dynamic>? _room;bool _loading=true;
@override void initState(){super.initState();_rooms=RoomService(Supabase.instance.client);_load();}
Future<void> _load()async{final r=await _rooms.roomSnapshot(widget.vaultId);if(mounted)setState((){_room=r;_loading=false;});}
Future<void> _edit()async{final title=TextEditingController(text:_room?['story_title']?.toString()??''),body=TextEditingController(text:_room?['story_body']?.toString()??'');final save=await showModalBottomSheet<bool>(context:context,isScrollControlled:true,builder:(c)=>Padding(padding:EdgeInsets.fromLTRB(20,20,20,MediaQuery.viewInsetsOf(c).bottom+24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('Write our story',style:Theme.of(c).textTheme.headlineSmall),const SizedBox(height:8),const Text('Both of you share this page. Write the story you want to remember together.'),const SizedBox(height:18),TextField(controller:title,maxLength:100,decoration:const InputDecoration(labelText:'Story title')),const SizedBox(height:10),TextField(controller:body,maxLength:5000,minLines:6,maxLines:12,decoration:const InputDecoration(labelText:'Our story')),const SizedBox(height:16),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Save our story'))])));if(save==true){await _rooms.updateStory(widget.vaultId,title:title.text,body:body.text);await _load();}}
@override Widget build(BuildContext context){if(_loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));final title=_room?['story_title']?.toString().trim()??'',body=_room?['story_body']?.toString().trim()??'';return Scaffold(appBar:AppBar(title:const Text('Our Story')),floatingActionButton:FloatingActionButton.extended(onPressed:_edit,icon:Icon(body.isEmpty?Icons.edit_outlined:Icons.auto_stories_outlined),label:Text(body.isEmpty?'Write our story':'Edit story')),body:ListView(padding:const EdgeInsets.fromLTRB(20,18,20,110),children:[Text('Our Story',style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:7),Text('One story, written by the two of you.',style:Theme.of(context).textTheme.bodyLarge),const SizedBox(height:22),if(body.isEmpty)Container(padding:const EdgeInsets.all(28),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFFFFEDF1),Color(0xFFFFF9F6)]),borderRadius:BorderRadius.circular(30)),child:Column(children:[const Icon(Icons.auto_stories_outlined,size:46),const SizedBox(height:14),Text('Your story is still unwritten',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:7),const Text('Start with how you met, what you love about your journey, or the moments that changed everything.',textAlign:TextAlign.center)]))else Card(child:Padding(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title.isEmpty?'The story of us':title,style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:14),Text(body,style:Theme.of(context).textTheme.bodyLarge)]))) ]));}}
