import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../services/room_service.dart';

class AnniversaryScreen extends StatefulWidget{const AnniversaryScreen({super.key,required this.vaultId});final String vaultId;@override State<AnniversaryScreen> createState()=>_AnniversaryScreenState();}
class _AnniversaryScreenState extends State<AnniversaryScreen>{late final RoomService _rooms;Map<String,dynamic>? _room;bool _loading=true;
@override void initState(){super.initState();_rooms=RoomService(Supabase.instance.client);_load();}
Future<void> _load()async{try{final r=await _rooms.roomSnapshot(widget.vaultId);if(mounted)setState(()=>_room=r);}finally{if(mounted)setState(()=>_loading=false);}}
DateTime? get _start=>DateTime.tryParse(_room?['relationship_started_on']?.toString()??'');
String _pretty(DateTime d){const m=['January','February','March','April','May','June','July','August','September','October','November','December'];return '${d.day} ${m[d.month-1]} ${d.year}';}
DateTime _anniversary(DateTime s,int y){if(s.month==2&&s.day==29)return DateTime(y,2,DateTime(y,3,0).day==29?29:28);return DateTime(y,s.month,s.day);}
@override Widget build(BuildContext context){if(_loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));final s=_start;final note=_room?['anniversary_note']?.toString().trim()??'';if(s==null)return Scaffold(appBar:AppBar(title:const Text('Anniversary')),body:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.calendar_month_outlined,size:54),const SizedBox(height:16),Text('Your date is waiting',style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:8),const Text('Add your relationship start date from Profile and it will appear here.',textAlign:TextAlign.center)])));final now=DateTime.now(),today=DateTime(now.year,now.month,now.day);var next=_anniversary(s,now.year);if(next.isBefore(today))next=_anniversary(s,now.year+1);final days=next.difference(today).inDays;final together=today.difference(DateTime(s.year,s.month,s.day)).inDays;return Scaffold(appBar:AppBar(title:const Text('Anniversary')),body:ListView(padding:const EdgeInsets.fromLTRB(20,18,20,50),children:[Text('Our Anniversary',style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:7),Text('A quiet place for the date that began your story.',style:Theme.of(context).textTheme.bodyLarge),const SizedBox(height:22),Container(padding:const EdgeInsets.all(26),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFFFFEDF1),Color(0xFFFFF9F6)]),borderRadius:BorderRadius.circular(30)),child:Column(children:[const Icon(Icons.favorite_rounded,size:34,color:Color(0xFFE9365A)),const SizedBox(height:12),Text(_pretty(s),textAlign:TextAlign.center,style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:6),const Text('The beginning of us'),const SizedBox(height:22),Row(children:[Expanded(child:_Stat(value:'$together',label:'days together')),const SizedBox(width:10),Expanded(child:_Stat(value:days==0?'Today':'$days',label:days==0?'our anniversary':'days to go'))])])),if(note.isNotEmpty)...[const SizedBox(height:18),Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('A note for us',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:8),Text(note,style:Theme.of(context).textTheme.bodyLarge)])))]]));}}
class _Stat extends StatelessWidget{const _Stat({required this.value,required this.label});final String value,label;@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.symmetric(vertical:16,horizontal:8),decoration:BoxDecoration(color:Colors.white.withValues(alpha:.78),borderRadius:BorderRadius.circular(20)),child:Column(children:[Text(value,style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:3),Text(label,textAlign:TextAlign.center)]));}
