import 'dart:async';
import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../services/room_service.dart';
import '../play/play_screen.dart';
import '../settings/settings_screen.dart';
import '../question_bank/question_bank_screen.dart';
import '../ask_me/ask_me_screen.dart';
import '../surprise/surprise_screen.dart';
import '../memories/memories_screen.dart';
import '../profile/profile_screen.dart';

class HomeShell extends StatefulWidget{const HomeShell({super.key,required this.room});final Map<String,dynamic> room;@override State<HomeShell> createState()=>_HomeShellState();}
class _HomeShellState extends State<HomeShell>{
 int _index=0;late final RoomService _rooms;late Map<String,dynamic> _room;Timer? _timer;
 static const _labels=['Us','Play','Ask','Memories','Surprises'];
 static const _icons=[Icons.favorite_border,Icons.casino_outlined,Icons.chat_bubble_outline,Icons.photo_outlined,Icons.card_giftcard_outlined];
 @override void initState(){super.initState();_room=Map.of(widget.room);_rooms=RoomService(Supabase.instance.client);_refresh();_timer=Timer.periodic(const Duration(seconds:15),(_)=>_refresh());}
 Future<void> _refresh() async{try{final r=await _rooms.roomSnapshot(widget.room['id'].toString());if(mounted)setState(()=>_room=r);}catch(_){}}
 @override void dispose(){_timer?.cancel();super.dispose();}
 @override Widget build(BuildContext context){final members=(_room['members'] as List?)??const[];final connected=members.length>=2;final id=_room['id'].toString();return Scaffold(
  appBar:AppBar(title:Text((_room['couple_title']?.toString().trim().isNotEmpty??false)?_room['couple_title'].toString():'Love Vault'),actions:[Padding(padding:const EdgeInsets.only(right:4),child:Center(child:Text(connected?'Together':'Waiting',style:Theme.of(context).textTheme.labelLarge))),Builder(builder:(c)=>IconButton(onPressed:()=>Scaffold.of(c).openEndDrawer(),icon:const Icon(Icons.menu_rounded)))]),
  endDrawer:Drawer(child:SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[Text('Just the two of you',style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:18),ListTile(leading:const Icon(Icons.person_outline),title:const Text('Profile'),onTap:(){Navigator.pop(context);Navigator.push(context,MaterialPageRoute(builder:(_)=>const ProfileScreen())).then((_)=>_refresh());}),ListTile(leading:const Icon(Icons.favorite_outline),title:const Text('Question Bank'),subtitle:const Text('Topics, custom questions & Spin'),onTap:(){Navigator.pop(context);Navigator.push(context,MaterialPageRoute(builder:(_)=>const QuestionBankScreen()));}),const Divider(),ListTile(leading:const Icon(Icons.settings_outlined),title:const Text('Settings'),onTap:(){Navigator.pop(context);Navigator.push(context,MaterialPageRoute(builder:(_)=>SettingsScreen(roomId:id)));})]))),
  body:IndexedStack(index:_index,children:[_UsPage(room:_room,onPlay:()=>setState(()=>_index=1)),PlayScreen(roomId:id),AskMeScreen(roomId:id),MemoriesScreen(roomId:id),SurpriseScreen(roomId:id)]),
  bottomNavigationBar:NavigationBar(selectedIndex:_index,onDestinationSelected:(v)=>setState(()=>_index=v),destinations:List.generate(_labels.length,(i)=>NavigationDestination(icon:Icon(_icons[i]),selectedIcon:Icon(_icons[i]),label:_labels[i]))));}
}

class _UsPage extends StatelessWidget{const _UsPage({required this.room,required this.onPlay});final Map<String,dynamic> room;final VoidCallback onPlay;
 DateTime? get _start=>DateTime.tryParse(room['relationship_started_on']?.toString()??'');
 String _pretty(DateTime d){const m=['January','February','March','April','May','June','July','August','September','October','November','December'];return '${d.day} ${m[d.month-1]} ${d.year}';}
 int _daysTogether(DateTime s){final n=DateTime.now();return DateTime(n.year,n.month,n.day).difference(DateTime(s.year,s.month,s.day)).inDays;}
 DateTime _anniversary(DateTime s,int y){if(s.month==2&&s.day==29)return DateTime(y,2,DateTime(y,3,0).day==29?29:28);return DateTime(y,s.month,s.day);}
 ({int days,DateTime date}) _next(DateTime s){final n=DateTime.now(),today=DateTime(DateTime.now().year,DateTime.now().month,DateTime.now().day);var x=_anniversary(s,n.year);if(x.isBefore(today))x=_anniversary(s,n.year+1);return(days:x.difference(today).inDays,date:x);}
 @override Widget build(BuildContext context){final ms=(room['members'] as List?)??const[];final me=ms.cast<dynamic>().where((m)=>m['user_id']==Supabase.instance.client.auth.currentUser?.id).cast<dynamic>().toList();final mine=me.isEmpty?null:me.first;final partner=ms.cast<dynamic>().where((m)=>m['user_id']!=Supabase.instance.client.auth.currentUser?.id).cast<dynamic>().toList();final other=partner.isEmpty?null:partner.first;final myName=mine?['display_name']?.toString()??'You';final nickname=mine?['nickname_for_partner']?.toString().trim()??'';final partnerName=nickname.isNotEmpty?nickname:(other?['display_name']?.toString()??'Your partner');final myAvatar=mine?['avatar_emoji']?.toString()??'♥';final partnerAvatar=other?['avatar_emoji']?.toString()??'♥';final start=_start;final next=start==null?null:_next(start);final note=room['anniversary_note']?.toString().trim()??'';return ListView(padding:const EdgeInsets.fromLTRB(20,20,20,110),children:[
  Row(children:[CircleAvatar(radius:25,child:Text(myAvatar,style:const TextStyle(fontSize:20))),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('$myName & $partnerName',style:Theme.of(context).textTheme.titleLarge),Text(start==null?'Your private space for two':'Together since ${_pretty(start)}')])),const SizedBox(width:10),CircleAvatar(radius:25,child:Text(partnerAvatar,style:const TextStyle(fontSize:20)))]),const SizedBox(height:22),
  InkWell(onTap:onPlay,borderRadius:BorderRadius.circular(30),child:Container(constraints:const BoxConstraints(minHeight:280),padding:const EdgeInsets.all(28),decoration:BoxDecoration(borderRadius:BorderRadius.circular(30),gradient:const LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:[Color(0xFFFFE7EC),Color(0xFFFFF7F4)])),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.casino_outlined,size:54,color:Color(0xFF8D2948)),const SizedBox(height:16),Text('Play together',style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:8),const Text('Spin a topic, answer one question at a time, then keep going with Next.',textAlign:TextAlign.center),const SizedBox(height:22),FilledButton.icon(onPressed:onPlay,icon:const Icon(Icons.play_arrow_rounded),label:const Text('Open Play & Spin'))]))),const SizedBox(height:18),
  Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(borderRadius:BorderRadius.circular(26),color:const Color(0xFFFFF1F4)),child:start==null?Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Our anniversary',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:6),const Text('Add your relationship date in Profile to start the anniversary countdown.')]):Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.calendar_month_outlined),const SizedBox(width:10),Text('Our anniversary',style:Theme.of(context).textTheme.titleLarge)]),const SizedBox(height:14),Text(_pretty(start),style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:12),Row(children:[Expanded(child:_MiniStat(value:'${_daysTogether(start)}',label:'days together')),const SizedBox(width:10),Expanded(child:_MiniStat(value:next!.days==0?'Today':'${next.days}',label:next.days==0?'anniversary':'days to go'))]),if(note.isNotEmpty)...[const SizedBox(height:14),Text(note,style:Theme.of(context).textTheme.bodyLarge)]])),
 ]);}
}
class _MiniStat extends StatelessWidget{const _MiniStat({required this.value,required this.label});final String value,label;@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.symmetric(vertical:14,horizontal:10),decoration:BoxDecoration(color:Colors.white.withValues(alpha:.72),borderRadius:BorderRadius.circular(18)),child:Column(children:[Text(value,style:Theme.of(context).textTheme.titleLarge),Text(label,textAlign:TextAlign.center)]));}
